// This file is auto-generated by @hey-api/openapi-ts

export const CreateItemSchema = {
	properties: {
		name: {
			type: 'string',
			minLength: 3,
			title: 'Name'
		}
	},
	type: 'object',
	required: ['name'],
	title: 'CreateItem'
} as const;

export const ErrorResponseModelSchema = {
	properties: {
		errors: {
			items: {
				additionalProperties: {
					type: 'string'
				},
				type: 'object'
			},
			type: 'array',
			title: 'Errors'
		}
	},
	type: 'object',
	required: ['errors'],
	title: 'ErrorResponseModel'
} as const;

export const HTTPValidationErrorSchema = {
	properties: {
		detail: {
			items: {
				$ref: '#/components/schemas/ValidationError'
			},
			type: 'array',
			title: 'Detail'
		}
	},
	type: 'object',
	title: 'HTTPValidationError'
} as const;

export const ItemSchema = {
	properties: {
		id: {
			anyOf: [
				{
					type: 'integer'
				},
				{
					type: 'null'
				}
			],
			title: 'Id'
		},
		name: {
			type: 'string',
			title: 'Name'
		}
	},
	type: 'object',
	required: ['name'],
	title: 'Item'
} as const;

export const ValidationErrorSchema = {
	properties: {
		loc: {
			items: {
				anyOf: [
					{
						type: 'string'
					},
					{
						type: 'integer'
					}
				]
			},
			type: 'array',
			title: 'Location'
		},
		msg: {
			type: 'string',
			title: 'Message'
		},
		type: {
			type: 'string',
			title: 'Error Type'
		}
	},
	type: 'object',
	required: ['loc', 'msg', 'type'],
	title: 'ValidationError'
} as const;
